version: "3.2"
services:
  neo4j:
    image: neo4j:latest
    container_name: 'quotes_neo4j'
    volumes:
      - '$HOME/neo4j/import:/var/lib/neo4j/import'
      - '$HOME/neo4j/plugins:/plugins'
      - '$HOME/neo4j/logs:/logs'
      - '$HOME/neo4j/data:/data'
    ports:
      - 7474:7474
      - 7687:7687
    restart: on-failure
    command: neo4j

  slack:
    container_name: 'quotes_graph_slack'
    build:
      context: .
      dockerfile: ./slack/Dockerfile
    depends_on: 
      - 'neo4j'
